# version format
version: 0.1.0-pre+{build}
os: Visual Studio 2015

install:
  - appveyor DownloadFile https://github.com/GrognardsFromHell/TemplePlusDependencies/releases/download/0.1/dependencies.7z
  - 7z x -odependencies dependencies.7z

build_script:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - msbuild TemplePlus.sln /p:Configuration=Release /p:MSBuildDefines="_TP_VERSION=%APPVEYOR_BUILD_VERSION%;_TP_COMMIT=%APPVEYOR_REPO_COMMIT%" /verbosity:minimal

after_build:
  - rd /s /q dist || cd .
  - mkdir dist
  - copy Release\TemplePlus.exe dist
  - xcopy /E /I tpdata dist\tpdata
  - xcopy /E /I dependencies\python-lib dist\tpdata\python-lib
  - 7z a TemplePlus-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\*

artifacts:
  - path: 'TemplePlus*.zip'
    name: TemplePlus

test: off
