# version format
version: 0.1.0-pre+{build}

install:
  - appveyor DownloadFile https://github.com/GrognardsFromHell/python-superstatic/releases/download/1.0.0/pythonstatic.7z
  - mkdir dependencies\python
  - 7z x -o dependencies\python pythonstatic.7z

build_script:
  - msbuild TemplePlus.sln /p:Configuration=Release /p:MSBuildDefines="_TP_VERSION=%APPVEYOR_BUILD_VERSION%;_TP_COMMIT=%APPVEYOR_REPO_COMMIT%" /verbosity:minimal

after_build:
  - rd /s /q dist
  - mkdir dist
  - copy Release\TemplePlus.exe dist
  - xcopy /E /I data dist\data
  - xcopy /E /I dependencies\python\python-lib dist\data\python-lib
  - 7z a TemplePlus-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\dist\*

artifacts:
  - path: 'TemplePlus*.zip'
    name: TemplePlus

test: off
